# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Load any of my config stuff
for config in "$HOME"/bashrc.d/*.bash ; do
      source "$config"
done
unset -v config
